
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  //I have no table name below, so that is why I have problem
  // return knex('table_name').del()
  // I have given table a name below
  return knex('Evo2').del()
    .then(function () {
      // Inserts seed entries
      //I have no table name below, so that is why I have problem
      // return knex('table_name').insert([
      // I have given table a name below
      return knex('Evo2').insert([
        
        {id: 1, 
          classic_ship_name: 'Fairstar',

          // Original Ship Data 
          original_ship_name: 'Oxfordshire',
          img: '/images/Evolution/Fairstar/Fairstar01.jpg',
          img_title: "Fairstar cruising off Pacific Islands in early 90's",
          img_trials: '',
          img_trials_title: '',
          img_early: '',
          img_early_title: '',
          early_service_years: '1957 to 1963',
          build_yard: 'Govan, Glasgow, Scotland | (by Fairfield Shipbuilding and Engineering Company)',
          original_operator: 'Bibby Line',
          registry_port: 'Monrovia, Liberia',
          cost: '',
          imo: '5267732',
          //original_passengers_max:
          passenger_capacity_full: '1500 (including 1000 troops)',
          crew_capacity: '409',
          gross_tonnage: '20586',
          length: '185.76 m (609 feet 5.4 inches)',
          beam: '23.86 m (78 feet 3.37 inches)',
          draft: '8.41 m (27 feet 7 inches)',
          height: '',
          funnel_height: '',
          //This space is where I have show more text, for when user wants to see more
          speed: '17 Knots (31 km/hr, 20 mph)',
          deadweight: '8500 Tonnes',
          lightship: '14250 estimate',
          loaded_displacement: '',
          power: '',
          power_rpm: '',
          fuel_capacity: '',
          fuel_consumption: '',
          fresh_water: '',
          propellors: '',
          propellor_size: '',
          rudder: '',
          rudder_size: '',
          decks: '10',
          accessible_decks: '',
          bridge_height: '',
          bridge_water: '', 
          shelter_deck: '',
          bow_bridge: '',
          bow_height: '',

          // Cruise Ship Information when it was a cruise ship
          cruise_ship_name: 'Fairstar',
          cruise_years: '1964 to 1997',
          cruise_operator: '1964 to 1997: Sitmar | 1989 to 1997: P & O Australia',
          cruise_reg_port: '',
          conversion_cost: '',
          cruise_passengers_max: '1868',
          cruise_crew_max: '460',
          cruise_gt: '',
          /* These below are extras, may not need all of them */
          cruise_funnel_hgt: '',
          cruise_speed: '',
          cruise_deadweight: '',
          cruise_lightship: '',
          cruise_displacement: '',
          cruise_power: '',
          cruise_power_rpm: '',
          cruise_fuel_capacity: '',
          cruise_fuel_consumption: '',
          cruise_fresh_water: '',
          cruise_propellors: '',
          cruise_propellor_size: '',
          cruise_rudder: '',
          cruise_rudder_size: '',
          cruise_decks: '',
          cruise_passenger_decks: '',
          cruise_bridge_height: '',
          cruise_bridge_water: '',
          cruise_shelter_deck: '',
          cruise_bow_bridge: '',
          cruise_bow_height: '',

          // Ship Specifications after lengthening
          // 1st_name_change: '',
          // 2nd_name_change: '',
          // 3rd_name_change: '',
          // 4th_name_change: '',
          // 5th_name_change: '',
          // 6th_name_change: '',
          // 7th_name_change: '',
          // 8th_name_change: '',
          // 9th_name_change: ''
          // Ship Names after lengthening
          name_after_lengthening: '',
          first_name_change: '',
          second_name_change: '',
          third_name_change: '',
          fourth_name_change: '',
          fifth_name_change: '',
          sixth_name_change: '',
          seventh_name_change: '',
          eighth_name_change: '',
          ninth_name_change: '',
          lengthened_service_yrs: '',
          // 3 new variables needed below
          lengthened_operator: '',
          lengthened_reg_port: '',
          lengthened_cost: '',

          lengthened_passengers: '',
          lengthened_crew: '',
          lengthened_gt: '',
          lengthened_length: '',
          // May not need lengthened_beam because the beam has not changed when it is lengthened
          lengthened_beam: '',
          lengthened_draft: '',
          lengthened_deadweight: '',
          lengthened_lightship: '',
          lengthened_displacement: '',
          /* These below are extras, may not need all of them */
          lengthened_funnel_hgt: '',
          lengthened_speed: '',
          lengthened_power: '',
          lengthened_power_rpm: '',
          lengthened_fuel_capacity: '', 
          lengthened_fuel_consumption: '', 
          lengthened_propellors: '',
          lengthened_propellor_size: '',
          lengthened_rudder: '',
          lengthened_rudder_size:'',
          lengthened_decks: '',
          lengthened_passenger_decks: '',
          lengthened_bridge_height: '',
          lengthened_bridge_water: '',
          lengthened_shelter_deck: '',
          lengthened_bow_bridge: '',
          lengthened_bow_height: '',


          // Ship Horn and section contents for each classic ship
          // Ship Page Contents like images, ship plans, paragraphs 
          ship_horn: '',
          early_1st_para: '',
          early_video: '',
          img_trials: '',
          img_trials_title: '',
          early_2nd_para: '',
          img_early: '',
          img_early_title: '',
          cruise_1st_para: '',
          img_1stcruise: '',
          img_1stcruise_title: '',
          cruise_2nd_para: '',
          cruise_video: '',
          mem_1st_para: '',
          mem_video: '',
          mem_2nd_para: '',
          plans_para: '',
          ship_plans: '',
          ship_plans_cont: '',
          final_1st_para: '',
          final_2nd_para:'',

        },

        {id: 2,
          classic_ship_name: 'Michelangelo',

          // Original Ship Data
          original_ship_name: '',
          img: '/images/Evolution/Michelangelo/michelangelo_1965_1.jpg',
          img_title: "Michelangelo cruising off Canary Islands in 1965",
          img_trials: '',
          img_trials_title: '',
          img_early: '',
          img_early_title: '',
          early_service_years: '',
          build_yard: 'Ansaldo Shipyards, Genoa, Italy',
          original_operator: '',
          registry_port: 'Genoa, Italy',
          cost: '$45 million',
          imo: '5234113',
          passenger_capacity_full: '1775  | 535 First Class | 550 Cabin Class | 690 Tourist Class',
          crew_capacity: '720',
          gross_tonnage: '45911',
          length: '276.2 m (906 feet 2 inches)',
          beam: '30.10 m (98 feet 9 inches)',
          draft: '10.41 m (34 feet 1 inch)',
          height: '52.60 m (167 feet)',
          funnel_height: '',
          //This space is where I have show more text, for when user wants to see more
          speed: '26.5 Knots (49.08 km/ hr or 30.50 mph)',
          deadweight: '9192 Tonnes',
          lightship: '35130 Tonnnes',
          loaded_displacement: '44322 Tonnes',
          power: '87000 Maximum Horsepower Imperial (64875.966 kW)',
          power_rpm: '',
          fuel_capacity: '',
          fuel_consumption: '',
          fresh_water: '',
          propellors: '',
          propellor_size: '',
          rudder: '',
          rudder_size: '',
          decks: '',
          accessible_decks: '',
          bridge_height: '',
          bridge_water: '', 
          shelter_deck: '',
          bow_bridge: '',
          bow_height: '',

          // Cruise Ship Information when it was a cruise ship
          cruise_ship_name: 'Michelangelo',
          cruise_years: '',
          cruise_operator: '',
          cruise_reg_port: '',
          conversion_cost: '',
          cruise_passengers_max: '1775  | 535 First Class | 550 Cabin Class | 690 Tourist Class',
          cruise_crew_max: '720',
          cruise_gt: '',
          /* These below are extras may not need all of them */
          cruise_funnel_hgt: '',
          cruise_speed: '',
          cruise_deadweight: '',
          cruise_lightship: '',
          cruise_displacement: '',
          cruise_power: '',
          cruise_power_rpm: '',
          cruise_fuel_capacity: '',
          cruise_fuel_consumption: '',
          cruise_fresh_water: '',
          cruise_propellors: '',
          cruise_propellor_size: '',
          cruise_rudder: '',
          cruise_rudder_size: '',
          cruise_decks: '',
          cruise_passenger_decks: '',
          cruise_bridge_height: '',
          cruise_bridge_water: '',
          cruise_shelter_deck: '',
          cruise_bow_bridge: '',
          cruise_bow_height: '',

          // Ship Specifications after lengthening
          // Ship Names after lengthening
          name_after_lengthening: '',
          first_name_change: '',
          second_name_change: '',
          third_name_change: '',
          fourth_name_change: '',
          fifth_name_change: '',
          sixth_name_change: '',
          seventh_name_change: '',
          eighth_name_change: '',
          ninth_name_change: '',
          lengthened_service_yrs: '',
          // 3 new variables needed below
          lengthened_operator: '',
          lengthened_reg_port: '',
          lengthened_cost: '',

          lengthened_passengers: '',
          lengthened_crew: '',
          lengthened_gt: '',
          lengthened_length: '',
          // May not need lengthened_beam because the beam has not changed when it is lengthened
          lengthened_beam: '',
          lengthened_draft: '',
          lengthened_deadweight: '',
          lengthened_lightship: '',
          lengthened_displacement: '',
          /* These below are extras, may not need all of them */
          lengthened_funnel_hgt: '',
          lengthened_speed: '',
          lengthened_power: '',
          lengthened_power_rpm: '',
          lengthened_fuel_capacity: '', 
          lengthened_fuel_consumption: '', 
          lengthened_propellors: '',
          lengthened_propellor_size: '',
          lengthened_rudder: '',
          lengthened_rudder_size:'',
          lengthened_decks: '',
          lengthened_passenger_decks: '',
          lengthened_bridge_height: '',
          lengthened_bridge_water: '',
          lengthened_shelter_deck: '',
          lengthened_bow_bridge: '',
          lengthened_bow_height: '',


          // Ship Horn and section contents for each classic ship
          // Ship Page Contents like images, ship plans, paragraphs 
          ship_horn: '',
          early_1st_para: '',
          early_video: '',
          img_trials: '',
          img_trials_title: '',
          early_2nd_para: '',
          img_early: '',
          img_early_title: '',
          cruise_1st_para: '',
          img_1stcruise: '',
          img_1stcruise_title: '',
          cruise_2nd_para: '',
          cruise_video: '',
          mem_1st_para: '',
          mem_video: '',
          mem_2nd_para: '',
          plans_para: '',
          ship_plans: '',
          ship_plans_cont: '',
          final_1st_para: '',
          final_2nd_para:'',

        },  

        {id: 3, 
          classic_ship_name: 'Queen Elizabeth 2',
          // Queen Elizabeth 2 (1969 to present)

          // Original Ship Data
          original_ship_name: '',
          img: '/images/Evolution/Qe2/5148955_orig.jpg',
          img_title: "Queen Elizabeth 2 in original colours, cruising off Canary Isles",
          img_trials: '',
          img_trials_title: '',
          img_early: '',
          img_early_title: '',
          early_service_years: '',
          build_yard: '',
          original_operator: '',
          registry_port: 'Southampton, UK (1969 to 2008) | Port Vila, Vanuatu (2008 to 2018) | Dubai, UAE (2018 to present)',
          cost: '29,091,000 British Pounds',
          imo: '6725418',
          passenger_capacity_full: '1892',
          crew_capacity: '1040',
          gross_tonnage: '1969 to 1994: 65863 | 1994 onwards: 70327',
          length: '293.52 m (963 feet)',
          beam: '32.07 m (105 feet 2.6 inches)',
          draft: '9.8 m (32 feet 1.8 inches)',
          height: '62.1 m (203 feet 8.88 inches)',
          funnel_height: '',
          //This space is where I have show more text, for when user wants to see more
          speed: 'Maximum 34 knots (63 km/ hr, 39 mph) | Cruising (Service): 28.5 knots (52.8 km/ hr, 32.8 mph)',
          deadweight: '11649 Tonnes',
          lightship: '38089 Tonnes',
          loaded_displacement: '49738 Tonnes',
          power: '88,000 kW (118,010 Horsepower)',
          power_rpm: '179rpm before 1987 refit',
          fuel_capacity: '4,381.4 tons',
          fuel_consumption: '18.05 tons per hour or 433 tons per day',
          fresh_water: '',
          propellors: '',
          propellor_size: '',
          rudder: '',
          rudder_size: '80 tons',
          decks: '12',
          accessible_decks: '',
          bridge_height: '',
          bridge_water: '', 
          shelter_deck: '',
          bow_bridge: '',
          bow_height: '',

          // Cruise Ship Information when it was a cruise ship
          cruise_ship_name: 'Queen Elizabeth 2',
          cruise_years: '',
          cruise_operator: '',
          cruise_reg_port: '',
          conversion_cost: '',
          cruise_passengers_max: '1775  | 535 First Class | 550 Cabin Class | 690 Tourist Class',
          cruise_crew_max: '720',
          cruise_gt: '',
          /* These below are extras may not need all of them */
          cruise_funnel_hgt: '',
          cruise_speed: '',
          cruise_deadweight: '',
          cruise_lightship: '',
          cruise_displacement: '',
          cruise_power: '',
          cruise_power_rpm: '',
          cruise_fuel_capacity: '',
          cruise_fuel_consumption: '',
          cruise_fresh_water: '',
          cruise_propellors: '',
          cruise_propellor_size: '',
          cruise_rudder: '',
          cruise_rudder_size: '',
          cruise_decks: '',
          cruise_passenger_decks: '',
          cruise_bridge_height: '',
          cruise_bridge_water: '',
          cruise_shelter_deck: '',
          cruise_bow_bridge: '',
          cruise_bow_height: '',
          
          // Ship Specifications after lengthening
          // Ship Names after lengthening
          name_after_lengthening: '',
          first_name_change: '',
          second_name_change: '',
          third_name_change: '',
          fourth_name_change: '',
          fifth_name_change: '',
          sixth_name_change: '',
          seventh_name_change: '',
          eighth_name_change: '',
          ninth_name_change: '',
          lengthened_service_yrs: '',
          // 3 new variables needed below
          lengthened_operator: '',
          lengthened_reg_port: '',
          lengthened_cost: '',

          lengthened_passengers: '',
          lengthened_crew: '',
          lengthened_gt: '',
          lengthened_length: '',
          // May not need lengthened_beam because the beam has not changed when it is lengthened
          lengthened_beam: '',
          lengthened_draft: '',
          lengthened_deadweight: '',
          lengthened_lightship: '',
          lengthened_displacement: '',
          /* These below are extras, may not need all of them */
          lengthened_funnel_hgt: '',
          lengthened_speed: '',
          lengthened_power: '',
          lengthened_power_rpm: '',
          lengthened_fuel_capacity: '', 
          lengthened_fuel_consumption: '', 
          lengthened_propellors: '',
          lengthened_propellor_size: '',
          lengthened_rudder: '',
          lengthened_rudder_size:'',
          lengthened_decks: '',
          lengthened_passenger_decks: '',
          lengthened_bridge_height: '',
          lengthened_bridge_water: '',
          lengthened_shelter_deck: '',
          lengthened_bow_bridge: '',
          lengthened_bow_height: '',

          // Ship Horn and section contents for each classic ship
          // Ship Page Contents like images, ship plans, paragraphs 
          ship_horn: '/videos/classics/QE2/QE2 Queen Elizabeth 2 Leaving Quebec City for Her last Time.mp4',
          early_1st_para: 'This is one of the famous well known ships here, as she was named after the most famous Queen of all time Queen Elizabeth 2 with her having the privilege of naming it and hit the champagne on the ship. Queen Elizabeth 2 ship began her maiden voyage on 2nd May 1969 from here home port Southampton to sail to New York City. She sailed under the UK flag being registered in Southampton and was with Cunard line. ',
          early_video: '',
          img_trials: '',
          img_trials_title: '',
          early_2nd_para: '',
          img_early: '',
          img_early_title: '',
          cruise_1st_para: '',
          img_1stcruise: '',
          img_1stcruise_title: '',
          cruise_2nd_para: '',
          cruise_video: '',
          mem_1st_para: '',
          mem_video: '',
          mem_2nd_para: '',
          plans_para: '',
          ship_plans: '/images/Evolution/Qe2/QE2CutawayQ.jpg',
          ship_plans_cont: '',
          final_1st_para: 'The Queen Elizabeth 2 was taken out of service in 2018 as a cruise ship, but instead of being scrapped she was now used as a floating hotel. She has been operating as a floating hotel in Port Rashid, Dubai, United Arab Emirates since 18th April 2018. ',
          final_2nd_para:'',

        },
        
        {id: 4,
          classic_ship_name: 'Song of Norway', 

          // Original Ship Data
          original_ship_name: 'Song of Norway (1970 to 1997)',
          img: '/images/image_manager__rex_thumbnail_images_song_of_norway_08.06.1994.jpg',
          img_title: "Song of Norway in Panama Canal 1994",
          img_trials: '',
          img_trials_title: '',
          img_early: '',
          img_early_title: '',
          early_service_years: '1970 to 1978',
          build_yard: 'Wartsilla Helsinki Shipyard, Finland',
          original_operator: 'Royal Caribbean (1970 to 1997)',
          registry_port: 'Oslo, Norway (1970 to 1997)',
          cost: '',
          imo: '7005190',
          passenger_capacity_full: '724',
          crew_capacity: '',
          gross_tonnage: '18416',
          length: '168.32 m (552 feet 2.75 inches)',
          beam: '23.96 m (78 feet 7.3 inches)',
          draft: '6.7 m ()',
          height: '',
          funnel_height: '',
          //This space is where I have show more text, for when user wants to see more
          speed: 'Cruising: 20.5 knots (38 km/hr, 23.6 mph)',
          deadweight: '3202 Tonnes',
          lightship: '',
          loaded_displacement: '',
          power: '14,560 kW (19,525.25 Horsepower)',
          power_rpm: '',
          fuel_capacity: '',
          fuel_consumption: '',
          fresh_water: '',
          propellors: '',
          propellor_size: '',
          rudder: '',
          rudder_size: '',
          decks: '',
          accessible_decks: '',
          bridge_height: '',
          bridge_water: '', 
          shelter_deck: '',
          bow_bridge: '',
          bow_height: '',

          // Cruise Ship Information when it was a cruise ship
          cruise_ship_name: 'Song of Norway',
          cruise_years: '',
          cruise_operator: '',
          cruise_reg_port: '',
          conversion_cost: '',
          cruise_passengers_max: '',
          cruise_crew_max: '',
          cruise_gt: '',
          /* These below are extras may not need all of them */
          cruise_funnel_hgt: '',
          cruise_speed: '',
          cruise_deadweight: '',
          cruise_lightship: '',
          cruise_displacement: '',
          cruise_power: '',
          cruise_power_rpm: '',
          cruise_fuel_capacity: '',
          cruise_fuel_consumption: '',
          cruise_fresh_water: '',
          cruise_propellors: '',
          cruise_propellor_size: '',
          cruise_rudder: '',
          cruise_rudder_size: '',
          cruise_decks: '',
          cruise_passenger_decks: '',
          cruise_bridge_height: '',
          cruise_bridge_water: '',
          cruise_shelter_deck: '',
          cruise_bow_bridge: '',
          cruise_bow_height: '',

          // Ship Specifications after lengthening
          // Ship Names after lengthening
          name_after_lengthening: 'Song of Norway (1978 to 1997)',
          first_name_change: 'Sundream (1997 to 2004)',
          second_name_change: 'Dream Princess (2004 to 2006)',
          third_name_change: 'Dream (2006 to 2007)',
          fourth_name_change: 'Clipper Pearl (2007 to 2008)',
          fifth_name_change: 'Clipper Pacific (2008 to 2009)',
          sixth_name_change: 'Festival (2009 to 2010)',
          seventh_name_change: 'Ocean Pearl (2010 to 2011)',
          eighth_name_change: 'Formosa Queen (2012 to 2013)',
          ninth_name_change: '',
          lengthened_service_yrs: '1978 to present',
          // 3 new variables needed below
          lengthened_operator: '',
          lengthened_reg_port: '',
          lengthened_cost: '',

          lengthened_passengers: '1196',
          lengthened_crew: '423',
          lengthened_gt: '22945',
          lengthened_length: '194.32 m (637 feet 6.4 inches)',
          // May not need lengthened_beam because the beam has not changed when it is lengthened
          lengthened_beam: '24 m (78 feet 8.8 inches)',
          lengthened_draft: '',
          lengthened_deadweight: '4,525 Tonnes',
          lengthened_lightship: '',
          lengthened_displacement: '',
          // May not need all of these details, because it may be same as original
          /* These below are extras, may not need all of them */
          lengthened_funnel_hgt: '',
          lengthened_speed: '',
          lengthened_power: '',
          lengthened_power_rpm: '',
          lengthened_fuel_capacity: '', 
          lengthened_fuel_consumption: '', 
          lengthened_propellors: '',
          lengthened_propellor_size: '',
          lengthened_rudder: '',
          lengthened_rudder_size:'',
          lengthened_decks: '',
          lengthened_passenger_decks: '',
          lengthened_bridge_height: '',
          lengthened_bridge_water: '',
          lengthened_shelter_deck: '',
          lengthened_bow_bridge: '',
          lengthened_bow_height: '',

          // Ship Horn and section contents for each classic ship
          // Ship Page Contents like images, ship plans, paragraphs 
          ship_horn: '',
          early_1st_para: '',
          early_video: '',
          img_trials: '',
          img_trials_title: '',
          early_2nd_para: '',
          img_early: '',
          img_early_title: '',
          cruise_1st_para: '',
          img_1stcruise: '',
          img_1stcruise_title: '',
          cruise_2nd_para: '',
          cruise_video: '',
          mem_1st_para: '',
          mem_video: '',
          mem_2nd_para: '',
          plans_para: '',
          ship_plans: '',
          ship_plans_cont: '',
          final_1st_para: '',
          final_2nd_para:'',

        }, 

        {id: 5,
          classic_ship_name: 'Royal Viking Sky',

          // Original Ship Data
          original_ship_name: 'Royal Viking Sky (1973 to 1991)',
          img: '/images/1757063.jpg',
          img_title: "Royal Viking Sky in Picton, New Zealand, March 1982",
          img_trials: '',
          img_trials_title: '',
          img_early: '',
          img_early_title: '',
          early_service_years: '1973 to 1982',
          build_yard: 'Wartsila Helsinki Shipyard, Helsinki, Finland',
          original_operator: 'Royal Viking Line (1973 to 1991)',
          registry_port: 'Bergen, Norway (1973 to 1987)',
          cost: '$22.5 million',
          imo: '7218395',
          passenger_capacity_full: '536',
          crew_capacity: '324',
          gross_tonnage: '21891',
          length: '177.70 m',
          beam: '25.19 m',
          draft: '7.00 m',
          height: '',
          funnel_height: '',
          //This space is where I have show more text, for when user wants to see more
          speed: 'Maximum: 21.5 knots (39.8 km/ hr or 24.7 mph)',
          deadweight: '3595 Tonnes',
          lightship: '13860 Tonnes',
          loaded_displacement: '17455 Tonnes',
          power: '13240 kW',
          power_rpm: '',
          fuel_capacity: '',
          fuel_consumption: '',
          fresh_water: '',
          propellors: '',
          propellor_size: '',
          rudder: '',
          rudder_size: '',
          decks: '',
          accessible_decks: '',
          bridge_height: '',
          bridge_water: '', 
          shelter_deck: '',
          bow_bridge: '',
          bow_height: '',

          // Cruise Ship Information when it was a cruise ship
          cruise_ship_name: 'Royal Viking Sky',
          cruise_years: '',
          cruise_operator: '',
          cruise_reg_port: '',
          conversion_cost: '',
          cruise_passengers_max: '',
          cruise_crew_max: '',
          cruise_gt: '',
          /* These below are extras, may not need all of them */
          cruise_funnel_hgt: '',
          cruise_speed: '',
          cruise_deadweight: '',
          cruise_lightship: '',
          cruise_displacement: '',
          cruise_power: '',
          cruise_power_rpm: '',
          cruise_fuel_capacity: '',
          cruise_fuel_consumption: '',
          cruise_fresh_water: '',
          cruise_propellors: '',
          cruise_propellor_size: '',
          cruise_rudder: '',
          cruise_rudder_size: '',
          cruise_decks: '',
          cruise_passenger_decks: '',
          cruise_bridge_height: '',
          cruise_bridge_water: '',
          cruise_shelter_deck: '',
          cruise_bow_bridge: '',
          cruise_bow_height: '',

          // Ship Specifications after lengthening
          // Ship Names after lengthening
          name_after_lengthening: 'Royal Viking Sky (1982 to 1991)', 
          first_name_change: 'Sunward (1991 to 1992)',
          second_name_change: 'Birka Queen (1992)',
          third_name_change: 'Sunward (1992 to 1993)',
          fourth_name_change: 'Golden Princess (1993 to 1997)',
          fifth_name_change: 'Superstar Capricorn (1997 to 1998)',
          sixth_name_change: 'Hyundai Keumgang (1998 to 2001)',
          seventh_name_change: 'Superstar Capricorn (2001 to 2004)',
          eighth_name_change: 'Grand Latino (2004 to 2005)',
          ninth_name_change: 'Boudicca (2005 to present)',
          lengthened_service_yrs: '1982 to present',
          // 3 new variables needed below
          lengthened_operator: '',
          lengthened_reg_port: '',
          lengthened_cost: '',

          lengthened_passengers: '900',
          lengthened_crew: '320',
          lengthened_gt: '28372',
          lengthened_length: '205.96 m (675 feet 8.66 inches)',
          // May not need lengthened_beam, because the beam has not changed when it is lengthened
          lengthened_beam: '25.19 m (82 feet 7.73 inches)',
          lengthened_draft: '7.55 m (24 feet 9.25 inches)',
          lengthened_deadweight: '5956 Tonnes',
          lengthened_lightship: '15760 Tonnes',
          lengthened_displacement: '21716 Tonnes',
          /* These below are extras, may not need all of them */
          lengthened_funnel_hgt: '',
          lengthened_speed: '',
          lengthened_power: '14000 kW',
          lengthened_speed: 'Maximum: 22 knots (41 km/ hr or 25 mph)',
          lengthened_fuel_capacity: '', 
          lengthened_fuel_consumption: '', 
          lengthened_propellors: '',
          lengthened_propellor_size: '',
          lengthened_rudder: '',
          lengthened_rudder_size:'',
          lengthened_decks: '',
          lengthened_passenger_decks: '',
          lengthened_bridge_height: '',
          lengthened_bridge_water: '',
          lengthened_shelter_deck: '',
          lengthened_bow_bridge: '',
          lengthened_bow_height: '',

          // Ship Horn and section contents for each classic ship
          // Ship Page Contents like images, ship plans, paragraphs 
          ship_horn: '',
          early_1st_para: '',
          early_video: '',
          img_trials: '',
          img_trials_title: '',
          early_2nd_para: '',
          img_early: '',
          img_early_title: '',
          cruise_1st_para: '',
          img_1stcruise: '',
          img_1stcruise_title: '',
          cruise_2nd_para: '',
          cruise_video: '',
          mem_1st_para: '',
          mem_video: '',
          mem_2nd_para: '',
          plans_para: '',
          ship_plans: '',
          ship_plans_cont: '',
          final_1st_para: '',
          final_2nd_para:'',

        },  

        {id: 6, 
          classic_ship_name: 'Allure of the Seas',

          // Original Ship Data
          original_ship_name: '',
          img: '/images/UFRPU.jpg',
          img_title: "Allure of the Seas maiden voyage celebration",
          img_trials: '',
          img_trials_title: '',
          img_early: '',
          img_early_title: '',
          early_service_years: '2010 to present',
          // May not need service_years below
          // service_years: '2010 to Present',
          build_yard: 'STX Europe Turku Shipyard, Finland',
          original_operator: '',
          cruise_operator: 'Royal Caribbean',
          registry_port: 'Miami, Florida, USA',
          cost: 'US $1 .2 Billion',
          imo: '9383948',
          passenger_capacity_full: '6780',
          crew_capacity: '2200',
          gross_tonnage: '225282',
          length: '362 m (1187 feet)',
          beam: '47 m (154 feet) 2.4 inches',
          draft: '9.322 m (30 feet 7 inches)',
          height: '72 m (236 feet 2.64 inches)',
          funnel_height: '',
          //This space is where I have show more text, for when user wants to see more
          speed: 'Maximum 22.6 knots (41.9 km/ hr, 26 mph)',
          deadweight: '19750 Tonnes',
          lightship: '80250 Tonnes',
          loaded_displacement: '100000 Tonnes',
          power: '97,000 kW',
          power_rpm: '',
          fuel_capacity: '',
          fuel_consumption: '',
          fresh_water: '',
          propellors: '',
          propellor_size: '',
          rudder: '',
          rudder_size: '',
          decks: '18',
          accessible_decks: '16',
          bridge_height: '',
          bridge_water: '', 
          shelter_deck: '',
          bow_bridge: '',
          bow_height: '',

          // Cruise Ship Information when it was a cruise ship
          cruise_ship_name: 'Allure of the Seas',
          cruise_years: '',
          cruise_operator: '',
          cruise_reg_port: '',
          conversion_cost: '',
          cruise_passengers_max: '',
          cruise_crew_max: '',
          cruise_gt: '',
          /* These below are extras, may not need all of them */
          cruise_funnel_hgt: '',
          cruise_speed: '',
          cruise_deadweight: '',
          cruise_lightship: '',
          cruise_displacement: '',
          cruise_power: '',
          cruise_power_rpm: '',
          cruise_fuel_capacity: '',
          cruise_fuel_consumption: '',
          cruise_fresh_water: '',
          cruise_propellors: '',
          cruise_propellor_size: '',
          cruise_rudder: '',
          cruise_rudder_size: '',
          cruise_decks: '',
          cruise_passenger_decks: '',
          cruise_bridge_height: '',
          cruise_bridge_water: '',
          cruise_shelter_deck: '',
          cruise_bow_bridge: '',
          cruise_bow_height: '',

          // Ship Specifications after lengthening
          // Ship Names after lengthening 
          name_after_lengthening: '',
          first_name_change: '',
          second_name_change: '',
          third_name_change: '',
          fourth_name_change: '',
          fifth_name_change: '',
          sixth_name_change: '',
          seventh_name_change: '',
          eighth_name_change: '',
          ninth_name_change: '', 
          lengthened_service_yrs: '',
          // 3 new variables needed below
          lengthened_operator: '',
          lengthened_reg_port: '',
          lengthened_cost: '',

          lengthened_passengers: '',
          lengthened_crew: '',
          lengthened_gt: '',
          lengthened_length: '',
          // May not need lengthened_beam because the beam has not changed when it is lengthened
          lengthened_beam: '',
          lengthened_draft: '',
          lengthened_deadweight: '',
          lengthened_lightship: '',
          lengthened_displacement: '',
          /* These below are extras, may not need all of them */
          lengthened_funnel_hgt: '',
          lengthened_speed: '',
          lengthened_power: '',
          lengthened_speed: '',
          lengthened_fuel_capacity: '', 
          lengthened_fuel_consumption: '', 
          lengthened_propellors: '',
          lengthened_propellor_size: '',
          lengthened_rudder: '',
          lengthened_rudder_size:'',
          lengthened_decks: '',
          lengthened_passenger_decks: '',
          lengthened_bridge_height: '',
          lengthened_bridge_water: '',
          lengthened_shelter_deck: '',
          lengthened_bow_bridge: '',
          lengthened_bow_height: '',

          // Ship Horn and section contents for each classic ship
          // Ship Page Contents like images, ship plans, paragraphs 
          ship_horn: '/videos/classics/Allure of the Seas/Allure of the Seas Departing Port Everglades with Horn Blasts.mp4',
          early_1st_para: '',
          early_video: '',
          img_trials: '',
          img_trials_title: '',
          early_2nd_para: '',
          img_early: '',
          img_early_title: '',
          cruise_1st_para: '',
          img_1stcruise: '',
          img_1stcruise_title: '',
          cruise_2nd_para: '',
          cruise_video: '',
          mem_1st_para: '',
          mem_video: '',
          mem_2nd_para: '',
          plans_para: '',
          ship_plans: '',
          ship_plans_cont: '',
          final_1st_para: '',
          final_2nd_para:'',
          
        },

      ]);
    });
};
