
exports.seed = function(knex, Promise) {
   // Deletes ALL existing entries
  return knex('Evo2').del()
    .then(function () {
        // Inserts seed entries
      return knex('Evo2').insert([
        { id: 1,
            ship_name: "Oxfordshire",
            service_years: "1957 to 1964",
            build_yard: " ",
            operator: "",
            registry_port: "",
            cost: "",
            imo: "",            
            passenger_full_capacity: "1300",
            crew_capacity:  "700",
            gross_tonnage: "21619",
            length: "185.76 m (609 feet 5.4 inches)",
            beam: "23.86 m (78 feet 3 inches)",
            draft: "8.41 m (27 feet 7 inches)",
            height: "47.85 m (167 feet)",

            //This space is where I have show more text, for when user wants to see more
            speed: "",
            deadweight: "8800 Tonnes",
            light_ship: "14250 Tonnes",
            loaded_displacement: "23050 Tonnes",
            power: "",
            fuel_type: "Marine Oil",
            fuel_capacity: " ",
            fuel_consumption: "",
            fresh_water: "",
            propellors: "",
            propellor_size: "",
            rudder: "",
            rudder_size: "",
            decks: "",
            accessible_decks: "",
            bridge_height: "",
            bridge_water: "",
            shelter_deck: "",
            bow_bridge: "",
            bow_height: "",

            // Below is Fairstar when Oxfordshire got converted to a cruise ship. 
            // She was still operating as a Steam Ship.
            ship_name_change: "Fairstar",
            img: "",
            img_title: "",
            service_years: "1964 to 1997",
            passenger_full_capacity: "1300",
            crew_capacity:  "700",
            gross_tonnage: "23169",
            length: "185.76 m (609 feet 5.4 inches)",
            beam: "23.86 m (78 feet 3 inches)",
            draft: "8.41 m (27 feet 7 inches)",
            height: "47.85 m (167 feet)",
            deadweight: "8800 Tonnes",
            light_ship: "14250 Tonnes",
            loaded_displacement: "23050 Tonnes"      

        },
        {id: 2,
            ship_name: "Michelangelo",
            service_years: "1965 to 1991",
            build_yard: " ",
            operator: "",
            registry_port: "",
            cost: "",
            imo: "",
            passenger_full_capacity: "1775",
            crew_capacity:  "720",
            gross_tonnage: "45911",
            length: "276.20 m (906 feet 2 inches)",
            beam: "30.10 m (89 feet 9 inches)",
            draft: "10.40 m (34 feet 1 inches)",
            height: "52.60 m (167 feet)",

            //This space is where I have show more text, for when user wants to see more
            speed: "",
            deadweight: "9192 Tonnes",
            light_ship: "35130 Tonnes",
            loaded_displacement: "44322 Tonnes",
            power: "",
            fuel_type: "Marine Oil",
            fuel_capacity: " ",
            fuel_consumption: "",
            fresh_water: "",
            propellors: "",
            propellor_size: "",
            rudder: "",
            rudder_size: "",
            decks: "",
            accessible_decks: "",
            bridge_height: "",
            bridge_water: "",
            shelter_deck: "",
            bow_bridge: "",
            bow_height: "",

        },

        {id: 3,
            ship_name: "QE2",
            service_years: "1969 to 2008",
            build_yard: "Clydebank, Scotland",
            operator: "",
            registry_port: "",
            cost: "",
            imo: "6725418",    
            passenger_full_capacity: "1892",
            crew_capacity:  "1040",
            gross_tonnage: "70327",
            length: "293.50 m (963 feet)",
            beam: "30.10 m (105 feet)",
            draft: "9.80 m (32 feet)",
            height: "62.10 m (203 feet 9 inches)",

            //This space is where I have show more text, for when user wants to see more
            speed: "",
            deadweight: "11639 Tonnes",
            light_ship: "38099 Tonnes",
            loaded_displacement: "49738 Tonnes",
            power: "",
            fuel_type: "Marine Oil",
            fuel_capacity: " ",
            fuel_consumption: "",
            fresh_water: "",
            propellors: "",
            propellor_size: "",
            rudder: "",
            rudder_size: "",
            decks: "",
            accessible_decks: "",
            bridge_height: "",
            bridge_water: "",
            shelter_deck: "",
            bow_bridge: "",
            bow_height: "",

        },

        {id: 4,
            ship_name: "Song of Norway",
            service_years: "1970 to 1978 (Before Lengthened)",
            passenger_full_capacity: "724",
            crew_capacity:  "400",
            gross_tonnage: "18416",
            length: "168.32 m (552 feet 2.77 inches)",
            beam: "23.96 m (78 feet 7.3 inches)",
            draft: "6.70 m (21 feet 11.78 inches)",
            height: "44.85 m (147 feet 1.75 inches)",

            speed: "",
            deadweight: "3202 Tonnes",
            light_ship: "12250 Tonnes",
            loaded_displacement: "15452 Tonnes",


            //After Lengthening
            ship_name_changes: "Sundream",

        },

        {id: 5,
            ship_name: "Royal Viking Sky",
            service_years: "1973 to 1982 (Before lengthening)",
            build_yard: " ",
            operator: "",
            registry_port: "",
            cost: "",
            imo: "",
            passenger_full_capacity: "536",
            crew_capacity:  "324",
            gross_tonnage: "21891",
            length: "177.74 m (583 feet 1.64 inches)",
            beam: "25.19 m (82 feet 8 inches)",
            draft: "7.00 m (23 feet)",
            height: "46.12 m (151 feet 3.75 inches)",
            speed: "",

            deadweight: "3595 Tonnes",
            light_ship: "13626 Tonnes",
            loaded_displacement: "17221 Tonnes",


            //After Lengthening
            ship_name_changes: "Royal Viking Sky (1982 to 1991)</br>Sunward (1991 to 1992)</br>Birka Queen (1992)</br>Sunward (1992 to 1993)</br>Golden Princess (1993 to 1997)</br>Superstar Capricorn (1997 to 1998)</br>Hyundai Keumgang (1998 to 2001)</br>Superstar Capricorn (2001 to 2004)</br>Grand Latino (2004 to 2005)</br>Boudicca (2005 to present)",
            new_service_years: "1982 to present (After Lengthening)",
            new_operator: "",
            new_registry_port: "",
            new_cost: "",
            passenger_full_capacity: "",
            crew_capacity:  "",
            changed_gt: "28372",
            changed_length: "205.96 m ( feet 1.64 inches)",
            changed_beam: "Same as before",
            changed_draft: "7.55 m (24 feet 9 inches)",
            changed_height: "Same as before",
            changed_dwt: "5956 Tonnes",
            changed_light_ship: "15760 Tonnes",
            changed_sloaded_displacement: "21716 Tonnes",

        },

        {id: 6,
            ship_name: "Allure of the Seas",
            service_years: "2010 to Present",
            build_yard: " ",
            operator: "",
            registry_port: "",
            cost: "",
            imo: "",
            passenger_full_capacity: "6780",
            crew_capacity:  "2200",
            gross_tonnage: "225282",
            length: "362.00 m (1187 feet)",
            beam: "47.00 m (154 feet 2.4 inches)",
            draft: "9.32 m (30 feet 7 inches)",
            height: "72.00 m (236 feet 2.64 inches)",

            //This space is where I have show more text, for when user wants to see more
            speed: "",
            deadweight: "19750 Tonnes",
            light_ship: "100000 Tonnes",
            loaded_displacement: "80250 Tonnes",
            power: "",
            fuel_type: "Marine Oil",
            fuel_capacity: " ",
            fuel_consumption: "",
            fresh_water: "",
            propellors: "",
            propellor_size: "",
            rudder: "",
            rudder_size: "",
            decks: "",
            accessible_decks: "",
            bridge_height: "",
            bridge_water: "",
            shelter_deck: "",
            bow_bridge: "",
            bow_height: "",

        }

      ]);
    });
};
