
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('table_name').del()
    .then(function () {
      // Inserts seed entries
      return knex('table_name').insert([
        {id: 1, 
          original_ship_name: 'Oxfordshire',
          img: '',
          img_title: '',
          img_trials: '',
          img_trials_title: '',
          img_early: '',
          img_early_title: '',
          early_service_years: '',
          build_yard: '',
          original_operator: 'Bibby Line',
          registry_port: '',
          cost: '',
          imo: '5267732',
          //original_passengers_max:
          passenger_capacity_full: '',
          crew_capacity: '',
          gross_tonnage: '',
          length: '',
          beam: '',
          draft: '',
          height: '',
          funnel_height: '',
          speed: '',
          deadweight: '',
          lightship: '',
          loaded_displacement: '',
          power: '',
          power_rpm: '',
          fuel_consumption: '',
          fresh_water: '',
          propellors: '',

          cruise_ship_name: 'Fairstar',
          cruise_passengers_max: '',
          cruise_crew_max: '',
          // 1st_name_change: '',
          // 2nd_name_change: '',
          // 3rd_name_change: '',
          // 4th_name_change: '',
          // 5th_name_change: '',
          // 6th_name_change: '',
          // 7th_name_change: '',
          // 8th_name_change: '',
          // 9th_name_change: ''
          name_after_lengthening: '',
          first_name_change: '',
          second_name_change: '',
          third_name_change: '',
          fourth_name_change: '',
          fifth_name_change: '',
          sixth_name_change: '',
          seventh_name_change: '',
          eighth_name_change: '',
          ninth_name_change: '',

          // Ship Specifications after lengthening
          lengthened_service_yrs: '',
          lengthened_passengers: '',
          lengthened_crew: '',
          lengthened_gt: '',
          lengthened_length: '',
          lengthened_beam: '',
          lengthened_draft: '',
          lengthened_deadweight: '',
          lengthened_lightship: '',
          lengthened_displacement: '',

          // Ship Horn and section contents for classic ship 
          ship_horn: '',
          early_1st_para: '',
          early_2nd_para: '',
          cruise_1st_para: '',
          cruise_2nd_para: '',
          mem_1st_para: '',
          mem_2nd_para: '',
          plans_para: '',
          final_1st_para: '',
          final_2nd_para:'',
          ship_plans: '',
          ship_plans_cont: '',
          early_video: '',
          cruise_video: '',
          mem_video: ''

        },

        {id: 2,
          cruise_ship_name: 'Michelangelo',
          original_ship_name: '',
          name_after_lengthening: '',
          first_name_change: '',
          second_name_change: '',
          third_name_change: '',
          fourth_name_change: '',
          fifth_name_change: '',
          sixth_name_change: '',
          seventh_name_change: '',
          eighth_name_change: '',
          ninth_name_change: '',
          // 1st_name_change: '',
          // 2nd_name_change: '',
          // 3rd_name_change: '',
          // 4th_name_change: '',
          // 5th_name_change: '',
          // 6th_name_change: '',
          // 7th_name_change: '',
          // 8th_name_change: '',
          // 9th_name_change: ''
          img: '',
          img_title: '',
          img_trials: '',
          img_trials_title: '',
          img_early: '',
          img_early_title: '',
          early_service_years: '',
          build_yard: '',
          original_operator: '',
          registry_port: '',
          cost: '',
          imo: '',
          passenger_capacity_full: '',
          crew_capacity: '',
          gross_tonnage: '',
          length: '',
          beam: '',
          draft: '',
          height: '',
          funnel_height: '',
          speed: '',
          deadweight: '',
          lightship: '',
          loaded_displacement: '',
          power: '',
          power_rpm: '',
          fuel_consumption: '',
          fresh_water: '',
          propellors: '',

          cruise_ship_name: '',
          cruise_passengers_max: '',
          cruise_crew_max: '',

          // Ship Specifications after lengthening
          lengthened_service_yrs: '',
          lengthened_passengers: '',
          lengthened_crew: '',
          lengthened_gt: '',
          lengthened_length: '',
          lengthened_beam: '',
          lengthened_draft: '',
          lengthened_deadweight: '',
          lengthened_lightship: '',
          lengthened_displacement: '',

          // Ship Horn and section contents for classic ship 
          ship_horn: '',
          early_1st_para: '',
          early_2nd_para: '',
          cruise_1st_para: '',
          cruise_2nd_para: '',
          mem_1st_para: '',
          mem_2nd_para: '',
          plans_para: '',
          final_1st_para: '',
          final_2nd_para:'',
          ship_plans: '',
          ship_plans_cont: '',
          early_video: '',
          cruise_video: '',
          mem_video: ''

        },  

        {id: 3, 
          cruise_ship_name: 'Queen Elizabeth 2',
          // Queen Elizabeth 2 (1969 to present)
          original_ship_name: '',
          name_after_lengthening: '',
          first_name_change: '',
          second_name_change: '',
          third_name_change: '',
          fourth_name_change: '',
          fifth_name_change: '',
          sixth_name_change: '',
          seventh_name_change: '',
          eighth_name_change: '',
          ninth_name_change: '',
          // 1st_name_change: '',
          // 2nd_name_change: '',
          // 3rd_name_change: '',
          // 4th_name_change: '',
          // 5th_name_change: '',
          // 6th_name_change: '',
          // 7th_name_change: '',
          // 8th_name_change: '',
          // 9th_name_change: ''
          img: '',
          img_title: '',
          img_trials: '',
          img_trials_title: '',
          img_early: '',
          img_early_title: '',
          early_service_years: '',
          build_yard: '',
          original_operator: '',
          registry_port: '',
          cost: '',
          imo: '',
          passenger_capacity_full: '',
          crew_capacity: '',
          gross_tonnage: '',
          length: '',
          beam: '',
          draft: '',
          height: '',
          funnel_height: '',
          speed: '',
          deadweight: '',
          lightship: '',
          loaded_displacement: '',
          power: '',
          power_rpm: '',
          fuel_consumption: '',
          fresh_water: '',
          propellors: '',

          cruise_ship_name: '',
          cruise_passengers_max: '',
          cruise_crew_max: '',          

          // Ship Specifications after lengthening
          lengthened_service_yrs: '',
          lengthened_passengers: '',
          lengthened_crew: '',
          lengthened_gt: '',
          lengthened_length: '',
          lengthened_beam: '',
          lengthened_draft: '',
          lengthened_deadweight: '',
          lengthened_lightship: '',
          lengthened_displacement: '',

          // Ship Horn and section contents for classic ship 
          ship_horn: '',
          early_1st_para: '',
          early_2nd_para: '',
          cruise_1st_para: '',
          cruise_2nd_para: '',
          mem_1st_para: '',
          mem_2nd_para: '',
          plans_para: '',
          final_1st_para: '',
          final_2nd_para:'',
          ship_plans: '',
          ship_plans_cont: '',
          early_video: '',
          cruise_video: '',
          mem_video: ''

        },
        
        {id: 4,
          cruise_ship_name: 'Song of Norway', 
          original_ship_name: 'Song of Norway (1970 to 1997)',
          img: '',
          img_title: '',
          img_trials: '',
          img_trials_title: '',
          img_early: '',
          img_early_title: '',
          early_service_years: '',
          build_yard: '',
          original_operator: '',
          registry_port: '',
          cost: '',
          imo: '',
          passenger_capacity_full: '',
          crew_capacity: '',
          gross_tonnage: '',
          length: '',
          beam: '',
          draft: '',
          height: '',
          funnel_height: '',
          speed: '',
          deadweight: '',
          lightship: '',
          loaded_displacement: '',
          power: '',
          power_rpm: '',
          fuel_consumption: '',
          fresh_water: '',
          propellors: '',

          cruise_ship_name: '',
          cruise_passengers_max: '',
          cruise_crew_max: '',

          // Ship Names after lengthening
          name_after_lengthening: 'Song of Norway (1978 tpo 1997)',
          first_name_change: 'Sundream (1997 to 2004)',
          second_name_change: 'Dream Princess (2004 to 2006)',
          third_name_change: 'Dream (2006 to 2007)',
          fourth_name_change: 'Clipper Pearl (2007 to 2008)',
          fifth_name_change: 'Clipper Pacific (2008 to 2009)',
          sixth_name_change: 'Festival (2009 to 2010)',
          seventh_name_change: 'Ocean Pearl (2010 to 2011)',
          eighth_name_change: 'Formosa Queen (2012 to 2013)',
          ninth_name_change: '',
          // 1st_name_change: '',
          // 2nd_name_change: '',
          // 3rd_name_change: '',
          // 4th_name_change: '',
          // 5th_name_change: '',
          // 6th_name_change: '',
          // 7th_name_change: '',
          // 8th_name_change: '',
          // 9th_name_change: ''

          // Ship Specifications after lengthening
          lengthened_service_yrs: '1978 to present',
          lengthened_passengers: '',
          lengthened_crew: '',
          lengthened_gt: '',
          lengthened_length: '',
          lengthened_beam: '',
          lengthened_draft: '',
          lengthened_deadweight: '',
          lengthened_lightship: '',
          lengthened_displacement: '',

          // Ship Horn and section contents for classic ship 
          ship_horn: '',
          early_1st_para: '',
          early_2nd_para: '',
          cruise_1st_para: '',
          cruise_2nd_para: '',
          mem_1st_para: '',
          mem_2nd_para: '',
          plans_para: '',
          final_1st_para: '',
          final_2nd_para:'',
          ship_plans: '',
          ship_plans_cont: '',
          early_video: '',
          cruise_video: '',
          mem_video: ''

        }, 

        {id: 5,
          cruise_ship_name: 'Royal Viking Sky',
          original_ship_name: 'Royal Viking Sky (1973 to 1991)',
          img: '',
          img_title: '',
          img_trials: '',
          img_trials_title: '',
          img_early: '',
          img_early_title: '',
          early_service_years: '',
          build_yard: '',
          original_operator: '',
          registry_port: '',
          cost: '',
          imo: '',
          passenger_capacity_full: '',
          crew_capacity: '',
          gross_tonnage: '',
          length: '',
          beam: '',
          draft: '',
          height: '',
          funnel_height: '',
          speed: '',
          deadweight: '',
          lightship: '',
          loaded_displacement: '',
          power: '',
          power_rpm: '',
          fuel_consumption: '',
          fresh_water: '',
          propellors: '',

          cruise_ship_name: '',
          cruise_passengers_max: '',
          cruise_crew_max: '',

          // Ship Names after lengthening
          name_after_lengthening: 'Royal Viking Sky (1982 to 1991)', 
          first_name_change: 'Sunward (1991 to 1992)',
          second_name_change: 'Birka Queen (1992)',
          third_name_change: 'Sunward (1992 to 1993)',
          fourth_name_change: 'Golden Princess (1993 to 1997)',
          fifth_name_change: 'Superstar Capricorn (1997 to 1998)',
          sixth_name_change: 'Hyundai Keumgang (1998 to 2001)',
          seventh_name_change: 'Superstar Capricorn (2001 to 2004)',
          eighth_name_change: 'Grand Latino (2004 to 2005)',
          ninth_name_change: 'Boudicca (2005 to present)',
          // 1st_name_change: '',
          // 2nd_name_change: '',
          // 3rd_name_change: '',
          // 4th_name_change: '',
          // 5th_name_change: '',
          // 6th_name_change: '',
          // 7th_name_change: '',
          // 8th_name_change: '',
          // 9th_name_change: ''

          // Ship Specifications after lengthening
          lengthened_service_yrs: '1982 to present',
          lengthened_passengers: '',
          lengthened_crew: '',
          lengthened_gt: '',
          lengthened_length: '',
          lengthened_beam: '',
          lengthened_draft: '',
          lengthened_deadweight: '',
          lengthened_lightship: '',
          lengthened_displacement: '',

          // Ship Horn and section contents for classic ship 
          ship_horn: '',
          early_1st_para: '',
          early_2nd_para: '',
          cruise_1st_para: '',
          cruise_2nd_para: '',
          mem_1st_para: '',
          mem_2nd_para: '',
          plans_para: '',
          final_1st_para: '',
          final_2nd_para:'',
          ship_plans: '',
          ship_plans_cont: '',
          early_video: '',
          cruise_video: '',
          mem_video: ''
        },  

        {id: 6, 
          cruise_ship_name: 'Allure of the Seas',
          original_ship_name: '',
          name_after_lengthening: '',
          first_name_change: '',
          second_name_change: '',
          third_name_change: '',
          fourth_name_change: '',
          fifth_name_change: '',
          sixth_name_change: '',
          seventh_name_change: '',
          eighth_name_change: '',
          ninth_name_change: '',  
          // 1st_name_change: '',
          // 2nd_name_change: '',
          // 3rd_name_change: '',
          // 4th_name_change: '',
          // 5th_name_change: '',
          // 6th_name_change: '',
          // 7th_name_change: '',
          // 8th_name_change: '',
          // 9th_name_change: ''

          img: '',
          img_title: '',
          img_trials: '',
          img_trials_title: '',
          img_early: '',
          img_early_title: '',
          early_service_years: '',
          build_yard: '',
          original_operator: '',
          registry_port: '',
          cost: '',
          imo: '',
          passenger_capacity_full: '',
          crew_capacity: '',
          gross_tonnage: '',
          length: '',
          beam: '',
          draft: '',
          height: '',
          funnel_height: '',
          speed: '',
          deadweight: '',
          lightship: '',
          loaded_displacement: '',
          power: '',
          power_rpm: '',
          fuel_consumption: '',
          fresh_water: '',
          propellors: '',

          // Ship Specifications after lengthening
          lengthened_service_yrs: '',
          lengthened_passengers: '',
          lengthened_crew: '',
          lengthened_gt: '',
          lengthened_length: '',
          lengthened_beam: '',
          lengthened_draft: '',
          lengthened_deadweight: '',
          lengthened_lightship: '',
          lengthened_displacement: '',

          // Ship Horn and section contents for classic ship 
          ship_horn: '',
          early_1st_para: '',
          early_2nd_para: '',
          cruise_1st_para: '',
          cruise_2nd_para: '',
          mem_1st_para: '',
          mem_2nd_para: '',
          plans_para: '',
          final_1st_para: '',
          final_2nd_para:'',
          ship_plans: '',
          ship_plans_cont: '',
          early_video: '',
          cruise_video: '',
          mem_video: ''

        },

      ]);
    });
};
