
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Reviews').del()
    .then(function () {
      // Inserts seed entries
      return knex('Reviews').insert([
        {id: 1, Review_User_Name: 'Robert Wilkinson', Review_Ship_Name: 'Symphony of the Seas',
                Review_img: '/images/Royal Caribbean/st-maarten-symphony-of-the-seas-950x530.jpg',
                Review: 'Amazingly big ship, so it was difficult to get to know everyone on board, like it is on the smaller ships. The activities however were excellent as there was a lot to choose from, like rock climbing, indoor cricket, tennis and touch rugby. The shows had lots of variety, ranging from argentinian and salsa dancing and singing from opera to songs with a comical side to them. I would recommend this ship to all variety of ages, as the passengers range from families, group of friends or loved ones on a trip.', 
                Star_Rating: '4.0', 
                Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '',
                Leaving_Port: '', Destination: '', Travel_Name: '', 
                Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                },
        {id: 2, Review_User_Name: 'Robert Wilkinson', Review_Ship_Name: 'Marella Celebration', 
                Review_img: '/images/611-62cc245f1327.jpg',
                Review: 'This ship has been sailing for Marella Cruises owned by UK company TUI. Since covid it is in retirement and is looking for a company to be sold to, so that it can continue cruising. When you click make a booking for this ship, the website tells you about what is happening with this ship.', 
                Star_Rating: '4.0', 
                Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '',
                Leaving_Port: '', Destination: '', Travel_Name: '', 
                Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                },
        {id: 3, Review_User_Name: '', Review_Ship_Name: 'Queen Mary 2',
                Review_img: '/images/cunard_cruise_line_queen_mary_2QM.jpg',
                Review:'', 
                Star_Rating: '', 
                Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                Leaving_Port: '', Destination: '', Travel_Name: '', 
                Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                },
        {id: 4, Review_User_Name: 'Robert Wilkinson', Review_Ship_Name: 'Star Princess',
                Review_img: '/images/_i4509460.jpg',
                Review: 'I did a recent cruise on Star Princess from Los Angeles to Santiago. I found that the Staff were very friendly and looked after you well. When I was on the cruise and forgot to get some water when I was eating from the buffet, this was absolutely no problem, as staff would approach me straight away to ask if I wanted some water and a coffee. The only exception, which we were not happy about was the room attendant, who frequently did not update our room with things like toilet paper, soap and making beds, so we had to tell another room attendant to get it sorted. Great range of activities to do on board at sea with lots of shows, quizzes, learning spanish and basketball free throw competition to name a few. The Italian captain is one of the funniest captains I have every seen and had a great sense of humour every time he talked on the mic. The ports of call were very unique and different with mostly great tours. The only tours I found disappointing were the day time tour in Lima, as we did not get to see much of the coast and did mostly a market tour. Also the tour in La Serena was a bit disappointing as it was scheduled to go to a Museum, but that never happened and instead we took a view from a Library to look out to La Serena. So choose your tours wisely or just do your own thing. Overall a great cruise and good value for money.', 
                Star_Rating: '4.6', 
                Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                Leaving_Port: '', Destination: '', Travel_Name: '', 
                Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                },
        {id: 5, Review_User_Name: '', Review_Ship_Name: 'Boudicca', 
                Review_img:'/images/Boudicca_at_Funchal_2016_(bigger).jpg',
                Review: '', 
                Star_Rating: '', 
                Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                Leaving_Port: '', Destination: '', Travel_Name: '', 
                Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                },
        {id: 6, Review_User_Name: '', Review_Ship_Name: 'Black Watch',
                Review_img: '/images/image_manager__rex_carousel_images_black_watch_approaching_port_of_hamburg_05._may_2016_13.jpg',
                Review:'', 
                Star_Rating: '', 
                Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '',
                Leaving_Port: '', Destination: '', Travel_Name: '', 
                Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                },
        {id: 7, Review_User_Name: '', Review_Ship_Name: 'Amadea', 
                Review_img: '/images/555-large-15de21c670ae7c3f6f3f1f37029303c9.jpg',
                Review:'', 
                Star_Rating: '', 
                Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                Leaving_Port: '', Destination: '', Travel_Name: '', 
                Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                },
        {id: 8, Review_User_Name: '', Review_Ship_Name: 'Majestic Princess', 
                Review_img: '/images/20180915-web-news-majestic-princess-sails-into-sydney-harbour-on-maiden-call-banner.jpg',
                Review:'', 
                Star_Rating: '', 
                Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                Leaving_Port: '', Destination: '', Travel_Name: '', 
                Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                },
        {id: 9, Review_User_Name: 'Robert Wilkinson', Review_Ship_Name: 'Viking Sun', 
                Review_img: '/images/78-b98894cfacc39.jpg',
                Review: 'Pretty much a brand new cruise, you will love this one.', 
                Star_Rating: '4.5', 
                Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                Leaving_Port: '', Destination: '', Travel_Name: '', 
                Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                },
        {id: 10,  Review_User_Name: '', Review_Ship_Name: 'Radiance of The Seas', 
                  Review_img: '/images/radiance-of-the-seas-d31_4933-med.jpg',
                  Review:'', 
                  Star_Rating: '', 
                  Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                  Leaving_Port: '', Destination: '', Travel_Name: '', 
                  Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                  },
        {id: 11,  Review_User_Name: 'Robert Wilkinson', Review_Ship_Name: 'Marella Discovery 2', 
                  Review_img: '/images/image_manager__rex_carousel_images_marella_discovery_2_auslaufend_havanna_23.02.2018_07.jpg',
                  Review: 'Enjoyed the range of activities on this ship. This classic liner from the 90s that used to be called Legend of The Seas, has a good range of activities for its size. It has a tennis court that was always available to use.', 
                  Star_Rating: '4.3', 
                  Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                  Leaving_Port: '', Destination: '', Travel_Name: '', 
                  Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                  },
        {id: 12,  Review_User_Name: '', Review_Ship_Name: 'Le Laperouse', 
                  Review_img: '/images/Ponant Cruises/50649869_401756037275665_4243685716581677093_n.jpg',
                  Review:'', 
                  Star_Rating: '', 
                  Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                  Leaving_Port: '', Destination: '', Travel_Name: '', 
                  Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                  },
        {id: 13,  Review_User_Name: '', Review_Ship_Name: 'Carnival Legend', 
                  Review_img: '/images/Carnival/carnival-legend-live-from.jpg',
                  Review:'', 
                  Star_Rating: '', 
                  Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                  Leaving_Port: '', Destination: '', Travel_Name: '', 
                  Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                  },
        {id: 14,  Review_User_Name: '', Review_Ship_Name: 'Carnival Vista',
                  Review_img: '/images/Carnival/carnival-blimp-02.gif',          
                  Review:'', 
                  Star_Rating: '', 
                  Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                  Leaving_Port: '', Destination: '', Travel_Name: '', 
                  Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                  },
        {id: 15,  Review_User_Name: '', Review_Ship_Name: 'Allure of The Seas', 
                  Review_img: '/images/Royal Caribbean/Allure-Of-The-Seas-Family-Featured-2-800x450.jpg',          
                  Review:'', 
                  Star_Rating: '', 
                  Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                  Leaving_Port: '', Destination: '', Travel_Name: '', 
                  Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                  },
        {id: 16,  Review_User_Name: '', Review_Ship_Name: 'Anthem of The Seas', 
                  Review_img: '/images/Royal Caribbean/p62cc88gq6311.jpg',
                  Review:'', 
                  Star_Rating: '', 
                  Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                  Leaving_Port: '', Destination: '', Travel_Name: '', 
                  Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                  },
        {id: 17,  Review_User_Name: '', Review_Ship_Name: 'Crystal Serenity', 
                  Review_img: '/images/Crystal Cruises/crystal-serenity.jpg',          
                  Review:'', 
                  Star_Rating: '', 
                  Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                  Leaving_Port: '', Destination: '', Travel_Name: '', 
                  Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                  },
        {id: 18,  Review_User_Name: '', Review_Ship_Name: 'Crystal Symphony', 
                  Review_img: '/images/Crystal Cruises/Crystal_Symphony_in_San_Francisco_299431.jpg',
                  Review:'', 
                  Star_Rating: '', 
                  Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                  Leaving_Port: '', Destination: '', Travel_Name: '', 
                  Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                  },
        {id: 19,  Review_User_Name: 'Robert Wilkinson', Review_Ship_Name: 'World Odyssey', 
                  Review_img: '/images/Semester at Sea/635906300054359048-001-worldodyssey.jpeg',
                  Review:'Operates world cruises of a different kind. It is serves as a travelling home and campus for students wanting to learn about different places.', 
                  Star_Rating: '4.3', 
                  Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                  Leaving_Port: '', Destination: '', Travel_Name: '', 
                  Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                  },
        {id: 20,  Review_User_Name: 'Robert Wilkinson', Review_Ship_Name: 'Celestyal Crystal', 
                  Review_img: '/images/Celestyal Cruises/Celestyal-Crystal.jpg',
                  Review: 'I have been on this ship on my Contiki tour, when it was cruising for Louis Cruise Lines. It visited some lovely destinations of Greece like Mykonos and highly recommended for younger travellers who want to have a good time.', 
                  Star_Rating: '4.1', 
                  Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                  Leaving_Port: '', Destination: '', Travel_Name: '', 
                  Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                  },
        {id: 21,  Review_User_Name: 'Robert Wilkinson', Review_Ship_Name: 'Celestyal Olympia', 
                  Review_img: '/images/Celestyal Cruises/celestyal-olympia-01.jpg',          
                  Review:'I have not been on this ship, but just like the one I have been on it used to operate under Louis Cruise Lines.', 
                  Star_Rating: '4.3', 
                  Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '',
                  Leaving_Port: '', Destination: '', Travel_Name: '', 
                  Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                  },
        {id: 22,  Review_User_Name: 'Robert Wilkinson', Review_Ship_Name: 'Explorer Dream', 
                  Review_img: '/images/Explorer Cruises/explorer-dream-620x330.jpg',
                  Review:'This ship has kept the same name and cruise line ever since it has been in service up until this year (2019). It used to be called Superstar Virgo and operated for Star Cruises. It has a beautiful asian feeling to it, as it sails a lot of Asian ports, but also most importantly this means that you will be well looked after at sea in terms of the hospitality. Meals were of top quality and the staff were very approachable. Unfortunately at the moment if you go to book, you will notice that all cruises for the 2020-21 season have been cancelled. Their will be an opportunity to travel in the future though when the situation is better.', 
                  Star_Rating: '4.5', 
                  Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                  Leaving_Port: '', Destination: '', Travel_Name: '', 
                  Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                  },
        {id: 23, Review_User_Name: '', Review_Ship_Name: 'Norwegian Spirit', 
                 Review_img: '/images/700x475_MainImage_Spirit2.jpg',
                 Review:'', 
                 Star_Rating: '', 
                 Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                 Leaving_Port: '', Destination: '', Travel_Name: '', 
                 Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                 },
        {id: 24, Review_User_Name: '', Review_Ship_Name: 'Norwegian Jewel', 
                 Review_img: '/images/Norwegian Jewel (Wellington, NZ) IMG_8841.JPG',
                 Review:'', 
                 Star_Rating: '', 
                 Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                 Leaving_Port: '', Destination: '', Travel_Name: '', 
                 Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                 },
        {id: 25, Review_User_Name: 'Robert Wilkinson', Review_Ship_Name: 'Norwegian Dawn',
                 Review_img: '/images/Norwegian Cruises/1280px-Norwegian_Dawn_Leaving_Boston_Harbor_(cropped).jpg',
                 Review:'I did a cruise on Norwegian Dawn in November 2019. The main great part of the cruise was that there was 9 ports calls on a 15 day cruise, so it was great to see that many beautiful places. The highlights were Curaco and Aruba. The main negative part of the cruise was that smoking was allowed in one of the lounges inside the ship and also in the casino, so for non smokers, the smoke smell was there when you were close to these parts of the ship. Food wise, the meat was very tender during dinner meals, so we were happy with that, but sometimes there not enough fruit.', 
                 Star_Rating: '4.4', 
                 Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                 Leaving_Port: '', Destination: '', Travel_Name: '', 
                 Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                 },
        {id: 26, Review_User_Name: '', Review_Ship_Name: 'Pacific Aria', 
                 Review_img: '/images/P & O Cruises/pacific-aria-po-australia-151464.jpg',
                 Review:'', 
                 Star_Rating: '', 
                 Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                 Leaving_Port: '', Destination: '', Travel_Name: '', 
                 Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                 },
        {id: 27, Review_User_Name: '', Review_Ship_Name: 'Pacific Dawn', 
                 Review_img: '/images/P & O Cruises/image_1000x500_21.webp',
                 Review:'', 
                 Star_Rating: '', 
                 Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                 Leaving_Port: '', Destination: '', Travel_Name: '', 
                 Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                 },
        {id: 28, Review_User_Name: '', Review_Ship_Name: 'Pacific Explorer', 
                 Review_img: '/images/P & O Cruises/PACEXP.jpg',
                 Review:'', 
                 Star_Rating: '', 
                 Cruise_Name: '', Sail_Date: '', Cruise_Year: '', Cruise_Month: '', 
                 Leaving_Port: '', Destination: '', Travel_Name: '', 
                 Review_Title: '', Number_of_Cruises: '', Travel_Party: ''
                 },
      ]);
    });
};
